[package]
name = "tag_game"
version = "0.1.0"
edition = "2018"
description = "Agent-Based implementation for the game \"Tag\""
repository = "https://github.com/TimDiekmann/TagGame"
license = "MIT OR Apache-2.0"
keywords = ["agent", "agent-based", "game", "tag"]
categories = ["games"]
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["serde"]

[[example]]
name = "tag"
required-features = ["serde"]
